name: ugc-alerts

services:
  ugc-alerts-cron:
    container_name: ugc-alerts-cron
    image: ugc-alerts-cron:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/ugc.db:/app/db/ugc.db
      - ./.env:/app/.env:ro
      - ./proxies.txt:/app/proxies.txt:ro
    restart: unless-stopped
